env:
  CMAKE_BUILD_TYPE:   Debug
  BUILD_TESTING:      "ON"
  ENABLE_SASL:        "ON"
  ENABLE_HASH_HSIEH:  "ON"
  ENABLE_DTRACE:      "ON"
  VERBOSE:            "ON"
  MEMCACHED_BINARY:   "/usr/local/bin/memcached"

task:
  name: Freebsd
  env:
    ports: RELEASE_12_1_0
  freebsd_instance:
    image_family: freebsd-12-1
  dependencies_script: |
    pkg update
    pkg upgrade -y
    pkg install -y \
      autotools \
      bison \
      cmake \
      cyrus-sasl \
      flex \
      libevent \
      pkgconf \
      subversion \
      sudo
  memcached_script: |
    svn co https://svn.freebsd.org/ports/tags/${ports}/databases/memcached memcached
    svn co https://svn.freebsd.org/ports/tags/${ports}/Mk /usr/ports/Mk
    svn co https://svn.freebsd.org/ports/tags/${ports}/Templates /usr/ports/Templates
    cd memcached
    echo bin/memcached > pkg-plist
    make all install SASLPWDB_CONFIGURE_ENABLE=sasl-pwdb OPTIONS_SET="SASL SASLPWDB" OPTIONS_DEFINE="SASL SASLPWDB"
    cd ..
  prepare_script: |
    mkdir build
    chown nobody build
    chsh -s /bin/sh nobody
  configure_script: |
    sudo -E -u nobody cmake -S . -B build
  build_script: |
    sudo -E -u nobody make -C build -j2 all
  test_script: |
    sudo -E -u nobody make -C build -j2 test/fast
  install_script: |
    sudo -E -u nobody make -C build install DESTDIR=/tmp
  on_failure:
    failed_script: |
      cat build/Testing/Temporary/LastTest.log || true
