services:
 - memcached

addons:
 apt:
  packages:
   - python-sphinx
   - valgrind
   - libevent-dev

dist: bionic
language: cpp
compiler:
 - gcc
 - clang

env:
# prod
 - 
# debug
 - enable_debug=yes
# sanitize=address
# - with_sanitize=address
# sanitize=thread
# - with_sanitize=thread

#before_install:
#install:

before_script:
 - export enable_dependency_tracking=no
 - autoreconf -vfi

#script:

#before_cache:
#after_success:

after_failure:
 - cat test-suite.log

#after_script:
