os: linux
dist: focal
language: cpp

jobs:
  include:
    - arch: arm64-graviton2
      virt: lxd
      group: edge
    - arch: arm64
    - arch: ppc64le
    - arch: s390x

branches:
  only:
    - v1.x
    - travis

addons:
  apt:
    packages:
      - libevent-dev
      - libsasl2-dev
      - libtbb-dev

env:
  - CMAKE_BUILD_TYPE=Debug BUILD_TESTING=true ENABLE_SASL=true ENABLE_HASH_HSIEH=true CFLAGS="-O0 --coverage" CXXFLAGS="-O0 --coverage"
  - CMAKE_BUILD_TYPE=Release ENABLE_SASL=true ENABLE_HASH_HSIEH=true

install:
  - |
    if test "$CMAKE_BUILT_TYPE" == "Debug"; then
      git clone --depth 1 -b 1.6.7 https://github.com/memcached/memcached
      cd memcached
      ./autogen.sh
      CFLAGS="-O2 -pipe" ./configure \
       --prefix=/opt \
       --disable-coverage \
       --disable-docs \
       --disable-dependency-tracking \
       --enable-sasl \
       --enable-sasl-pwdb \
       ;
      make -j2
      make install
      cd ..
    endif

before_script:
  - mkdir build

script:
  - |
    cd build
    if test "$CMAKE_BUILD_TYPE" == "Debug"; then
      cmake -DMEMCACHED_BINARY=/opt/bin/memcached ..
      make -j2 VERBOSE=1
      make test VERBOSE=1
      make install DESTDIR=/tmp
    else
      cmake ..
      make -j2
      make package
      cmake -DCPACK_COMPONENT_INSTALL=ON .
      make package
    fi

after_failure:
  - test "$CMAKE_BUILD_TYPE" == "Debug" && cat Testing/Temporary/LastTest.log || true

after_success:
  - test "$CMAKE_BUILD_TYPE" == "Debug" && bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/796c8423962228333c54
    on_success: always
    on_failure: change
    on_start: never
