services:
 - memcached

addons:
 apt:
  packages:

dist: bionic
language: cpp
compiler:
 - gcc
 - clang

env:
# prod
 - enable_debug=no enable_assert=no enable_dtrace=no enable_silent_rules=yes ac_cv_vcs_system=none
# debug
 - enable_debug=yes enable_assert=yes enable_dtrace=yes enable_silent_rules=no
# sanitize=address
 - with_sanitize=address
# sanitize=thread
 - with_sanitize=thread

#before_install:
#install:

before_script:
 - export enable_dependency_tracking=no
 - autoreconf -vfi

#script:

#before_cache:
#after_success:
#after_failure:
#after_script:
