os: linux
dist: focal
arch: arm64
language: cpp

addons:
 apt:
  packages:
   - libevent-dev
   - libsasl2-dev

env:
 - CMAKE_BUILD_TYPE=Debug BUILD_TESTING=true ENABLE_SASL=true

install:
 - |
   git clone --depth 1 -b 1.6.7 https://github.com/memcached/memcached
   cd memcached
   ./autogen.sh
   CFLAGS="-O2 -pipe" ./configure \
     --prefix=/opt \
     --disable-coverage \
     --disable-docs \
     --disable-dependency-tracking \
     --enable-sasl \
     --enable-sasl-pwdb \
     ;
   make -j2
   make install
   cd ..

before_script:
 - mkdir build

script:
 - cd build
 - cmake -DMEMCACHED_BINARY=/opt/bin/memcached ..
 - make -j2 VERBOSE=1
 - make test VERBOSE=1
 - make install DESTDIR=.

after_failure:
 - cat Testing/Temporary/LastTest.log || true
