services:
 - memcached

addons:
 apt:
  packages:
   - python-sphinx
   - valgrind
   - libevent-dev
   - libsasl2-dev

dist: bionic
language: cpp
compiler:
 - gcc
 - clang

env:
 - BUILD=Release SASL=false
 - BUILD=Debug SASL=true PREFIX=/opt PORT=11212

#before_install:
install:
 - |
   if ${SASL};
   then
     git clone -b 1.5.9 https://github.com/memcached/memcached &&
     cd memcached && ./autogen.sh &&
     CFLAGS="-O2 -pipe" ./configure --prefix=${PREFIX} --disable-dependency-tracking --enable-sasl --enable-sasl-pwdb --disable-coverage --disable-docs &&
     make -j2 && make install;
     ${PREFIX}/bin/memcached -l 127.0.0.1 -p ${PORT} -U ${PORT} -m 128 &
   fi;


before_script:
 - echo stats settings | nc -q 0 localhost ${PORT:-11211} | column -t
 - mkdir build

script:
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=${BUILD} -DENABLE_SASL=${SASL} -DMEMCACHED_BINARY=${PREFIX:-/usr}/bin/memcached ..
 - make -j2
 - make test
 - make install DESTDIR=.

#before_cache:
#after_success:

after_failure:
 - cat Testing/Temporary/LastTest.log

#after_script:
