services:
 - memcached

addons:
 apt:
  packages:
   - python-sphinx
   - valgrind
   - libevent-dev

dist: bionic
language: cpp
compiler:
 - gcc
 - clang

env:
# prod
 - BUILD=Release
 - BUILD=Debug

#before_install:
#install:

before_script:
 - memcached-tool localhost:11211 settings
 - mkdir build

script:
 - cmake -B build -S . -DCMAKE_BUILD_TYPE=${BUILD}
 - make -C build
 - make -C build test

#before_cache:
#after_success:

after_failure:
 - cat build/Testing/Temporary/LastTest.log

#after_script:
