services:
 - memcached

addons:
 apt:
  packages:
   - python-sphinx
   - valgrind
   - libevent-dev

dist: bionic
language: cpp
compiler:
 - gcc
 - clang

env:
# prod
 - BUILD=Release
 - BUILD=Debug

#before_install:
#install:

before_script:
 - echo stats settings | nc -q 0 localhost 11211 | column -t
 - mkdir build

script:
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=${BUILD} ..
 - make
 - make test
 - make install DESTDIR=.

#before_cache:
#after_success:

after_failure:
 - cat build/Testing/Temporary/LastTest.log

#after_script:
